package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;

public final class zzco<R extends Result> extends OptionalPendingResult<R> {
    private final BasePendingResult<R> f17304a;

    public zzco(PendingResult<R> pendingResult) {
        if (pendingResult instanceof BasePendingResult) {
            this.f17304a = (BasePendingResult) pendingResult;
            return;
        }
        throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }

    public final R mo1541a(long j, TimeUnit timeUnit) {
        return this.f17304a.mo1541a(j, timeUnit);
    }

    public final void mo1542a(zza com_google_android_gms_common_api_PendingResult_zza) {
        this.f17304a.mo1542a(com_google_android_gms_common_api_PendingResult_zza);
    }

    public final void mo1543a(ResultCallback<? super R> resultCallback) {
        this.f17304a.mo1543a((ResultCallback) resultCallback);
    }

    public final boolean mo3414a() {
        return this.f17304a.m12829a();
    }

    public final R mo3415b() {
        if (mo3414a()) {
            return mo1541a(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public final void mo1544c() {
        this.f17304a.mo1544c();
    }

    public final boolean mo1545d() {
        return this.f17304a.mo1545d();
    }

    public final Integer mo1546e() {
        return this.f17304a.mo1546e();
    }
}
