package android.support.constraint.solver;

import java.util.ArrayList;

public class Metrics {
    public long f214A;
    public long f215a;
    public long f216b;
    public long f217c;
    public long f218d;
    public long f219e;
    public long f220f;
    public long f221g;
    public long f222h;
    public long f223i;
    public long f224j;
    public long f225k;
    public long f226l;
    public long f227m;
    public long f228n;
    public long f229o;
    public long f230p;
    public long f231q;
    public long f232r;
    public long f233s;
    public long f234t;
    public long f235u;
    public long f236v;
    public long f237w;
    public long f238x;
    public long f239y;
    public ArrayList<String> f240z;

    public String toString() {
        StringBuilder stringBuilder = new StringBuilder("\n*** Metrics ***\ntable increases: ");
        stringBuilder.append(this.f215a);
        stringBuilder.append("\nmaxTableSize: ");
        stringBuilder.append(this.f227m);
        stringBuilder.append("\nmaxVariables: ");
        stringBuilder.append(this.f232r);
        stringBuilder.append("\nmaxRows: ");
        stringBuilder.append(this.f233s);
        stringBuilder.append("\n\nminimize: ");
        stringBuilder.append(this.f216b);
        stringBuilder.append("\nminimizeGoal: ");
        stringBuilder.append(this.f231q);
        stringBuilder.append("\nconstraints: ");
        stringBuilder.append(this.f217c);
        stringBuilder.append("\nsimpleconstraints: ");
        stringBuilder.append(this.f218d);
        stringBuilder.append("\noptimize: ");
        stringBuilder.append(this.f219e);
        stringBuilder.append("\niterations: ");
        stringBuilder.append(this.f220f);
        stringBuilder.append("\npivots: ");
        stringBuilder.append(this.f221g);
        stringBuilder.append("\nbfs: ");
        stringBuilder.append(this.f222h);
        stringBuilder.append("\nvariables: ");
        stringBuilder.append(this.f223i);
        stringBuilder.append("\nerrors: ");
        stringBuilder.append(this.f224j);
        stringBuilder.append("\nslackvariables: ");
        stringBuilder.append(this.f225k);
        stringBuilder.append("\nextravariables: ");
        stringBuilder.append(this.f226l);
        stringBuilder.append("\nfullySolved: ");
        stringBuilder.append(this.f228n);
        stringBuilder.append("\ngraphOptimizer: ");
        stringBuilder.append(this.f229o);
        stringBuilder.append("\nresolvedWidgets: ");
        stringBuilder.append(this.f230p);
        stringBuilder.append("\noldresolvedWidgets: ");
        stringBuilder.append(this.f238x);
        stringBuilder.append("\nnonresolvedWidgets: ");
        stringBuilder.append(this.f239y);
        stringBuilder.append("\ncenterConnectionResolved: ");
        stringBuilder.append(this.f234t);
        stringBuilder.append("\nmatchConnectionResolved: ");
        stringBuilder.append(this.f235u);
        stringBuilder.append("\nchainConnectionResolved: ");
        stringBuilder.append(this.f236v);
        stringBuilder.append("\nbarrierConnectionResolved: ");
        stringBuilder.append(this.f237w);
        stringBuilder.append("\nproblematicsLayouts: ");
        stringBuilder.append(this.f240z);
        stringBuilder.append("\n");
        return stringBuilder.toString();
    }
}
