package com.google.android.gms.internal;

import android.content.Context;
import android.content.SharedPreferences.Editor;
import io.fabric.sdk.android.services.common.AbstractSpiCall;
import io.fabric.sdk.android.services.events.EventsFilesManager;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.jcodec.codecs.common.biari.MQEncoder;
import org.json.JSONObject;

@zzzv
public final class zznh {
    public static final zzmx<String> f7865A = zzmx.m6479a(1, "gads:video:codec_query_mime_types", "");
    public static final zzmx<Integer> f7866B = zzmx.m6476a(1, "gads:video:codec_query_minimum_version", 16);
    public static final zzmx<Boolean> f7867C = zzmx.m6478a(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> f7868D = zzmx.m6478a(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
    public static final zzmx<String> f7869E = zzmx.m6479a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final zzmx<String> f7870F = zzmx.m6479a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final zzmx<String> f7871G = zzmx.m6479a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final zzmx<Boolean> f7872H = zzmx.m6478a(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
    public static final zzmx<String> f7873I = zzmx.m6479a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final zzmx<Boolean> f7874J = zzmx.m6478a(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
    public static final zzmx<Boolean> f7875K = zzmx.m6478a(0, "gads:enable_content_fetching", Boolean.valueOf(true));
    public static final zzmx<Integer> f7876L = zzmx.m6476a(0, "gads:content_length_weight", 1);
    public static final zzmx<Integer> f7877M = zzmx.m6476a(0, "gads:content_age_weight", 1);
    public static final zzmx<Integer> f7878N = zzmx.m6476a(0, "gads:min_content_len", 11);
    public static final zzmx<Integer> f7879O = zzmx.m6476a(0, "gads:fingerprint_number", 10);
    public static final zzmx<Integer> f7880P = zzmx.m6476a(0, "gads:sleep_sec", 10);
    public static final zzmx<Boolean> f7881Q = zzmx.m6478a(1, "gads:enable_content_url_hash", Boolean.valueOf(true));
    public static final zzmx<Integer> f7882R = zzmx.m6476a(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzmx<Boolean> f7883S = zzmx.m6478a(1, "gads:enable_content_vertical_hash", Boolean.valueOf(true));
    public static final zzmx<Integer> f7884T = zzmx.m6476a(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzmx<Integer> f7885U = zzmx.m6476a(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzmx<String> f7886V = zzmx.m6479a(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzmx<String> f7887W = zzmx.m6479a(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final zzmx<Boolean> f7888X = zzmx.m6478a(0, "gad:app_index_enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> f7889Y = zzmx.m6478a(1, "gads:content_fetch_disable_get_title_from_webview", Boolean.valueOf(false));
    public static final zzmx<Boolean> f7890Z = zzmx.m6478a(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
    public static final zzmx<String> f7891a = zzmx.m6479a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    public static final zzmx<Boolean> aA = zzmx.m6478a(1, "gads:enable_ad_loader_manager", Boolean.valueOf(true));
    public static final zzmx<Boolean> aB = zzmx.m6478a(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(false));
    public static final zzmx<Long> aC = zzmx.m6477a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final zzmx<Boolean> aD = zzmx.m6478a(1, "gads:interstitial_ad_immersive_mode", Boolean.valueOf(true));
    public static final zzmx<Boolean> aE = zzmx.m6478a(1, "gads:custom_close_blocking:enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> aF = zzmx.m6478a(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> aG = zzmx.m6478a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
    public static final zzmx<String> aH = zzmx.m6479a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final zzmx<String> aI = zzmx.m6479a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final zzmx<Integer> aJ = zzmx.m6476a(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final zzmx<Integer> aK = zzmx.m6476a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final zzmx<Integer> aL = zzmx.m6476a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final zzmx<String> aM = zzmx.m6479a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final zzmx<Integer> aN = zzmx.m6476a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final zzmx<Integer> aO = zzmx.m6476a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final zzmx<Long> aP = zzmx.m6477a(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    public static final zzmx<Long> aQ = zzmx.m6477a(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    public static final zzmx<Float> aR = zzmx.m6475a(1, "gads:interstitial_ad_pool:discard_asymptote");
    public static final zzmx<Float> aS = zzmx.m6475a(1, "gads:interstitial_ad_pool:miss_asymptote");
    public static final zzmx<Boolean> aT = zzmx.m6478a(0, "gads:debug_logging_feature:enable", Boolean.valueOf(false));
    public static final zzmx<Boolean> aU = zzmx.m6478a(0, "gads:debug_logging_feature:intercept_web_view", Boolean.valueOf(false));
    public static final zzmx<String> aV = zzmx.m6479a(1, "gads:spherical_video:vertex_shader", "");
    public static final zzmx<String> aW = zzmx.m6479a(1, "gads:spherical_video:fragment_shader", "");
    public static final zzmx<Boolean> aX = zzmx.m6478a(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> aY = zzmx.m6478a(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
    public static final zzmx<Long> aZ = zzmx.m6477a(1, "gads:position_watcher:throttle_ms", 200);
    public static final zzmx<Long> aa = zzmx.m6477a(0, "gads:app_index:timeout_ms", 1000);
    public static final zzmx<Boolean> ab = zzmx.m6478a(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> ac = zzmx.m6478a(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
    public static final zzmx<Boolean> ad = zzmx.m6478a(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
    public static final zzmx<Boolean> ae = zzmx.m6478a(0, "gads:ad_key_enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> af = zzmx.m6478a(1, "gads:sai:enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> ag = zzmx.m6478a(1, "gads:sai:banner_ad_enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> ah = zzmx.m6478a(1, "gads:sai:native_ad_enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> ai = zzmx.m6478a(1, "gads:sai:interstitial_ad_enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> aj = zzmx.m6478a(1, "gads:sai:rewardedvideo_ad_enabled", Boolean.valueOf(true));
    public static final zzmx<String> ak = zzmx.m6479a(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final zzmx<String> al = zzmx.m6479a(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    public static final zzmx<Boolean> am = zzmx.m6478a(1, "gads:sai:click_gmsg_enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> an = zzmx.m6478a(1, "gads:sai:using_macro:enabled", Boolean.valueOf(false));
    public static final zzmx<String> ao = zzmx.m6479a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final zzmx<Long> ap = zzmx.m6477a(1, "gads:sai:timeout_ms", -1);
    public static final zzmx<Integer> aq = zzmx.m6476a(1, "gads:sai:scion_thread_pool_size", 5);
    public static final zzmx<Boolean> ar = zzmx.m6478a(1, "gads:webview:ignore_over_scroll", Boolean.valueOf(true));
    public static final zzmx<Boolean> as = zzmx.m6478a(1, "gads:rewarded:adapter_initialization_enabled", Boolean.valueOf(false));
    public static final zzmx<Long> at = zzmx.m6477a(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final zzmx<Boolean> au = zzmx.m6478a(1, "gads:app_activity_tracker:enabled", Boolean.valueOf(true));
    public static final zzmx<Long> av = zzmx.m6477a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final zzmx<Long> aw = zzmx.m6477a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzmx<Boolean> ax = zzmx.m6478a(1, "gads:adid_values_in_adrequest:enabled", Boolean.valueOf(false));
    public static final zzmx<Long> ay = zzmx.m6477a(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final zzmx<Boolean> az = zzmx.m6478a(1, "gads:disable_adid_values_in_ms", Boolean.valueOf(false));
    public static final zzmx<Boolean> f7892b = zzmx.m6478a(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> bA = zzmx.m6478a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> bB = zzmx.m6478a(0, "gass:enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> bC = zzmx.m6478a(0, "gass:enable_int_signal", Boolean.valueOf(true));
    public static final zzmx<Boolean> bD = zzmx.m6478a(0, "gass:enable_ad_attestation_signal", Boolean.valueOf(true));
    public static final zzmx<Boolean> bE = zzmx.m6478a(0, "gads:support_screen_shot", Boolean.valueOf(true));
    public static final zzmx<Boolean> bF = zzmx.m6478a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
    public static final zzmx<String> bG = zzmx.m6479a(1, "gads:sdk_core_constants:caps", "");
    public static final zzmx<Long> bH = zzmx.m6477a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final zzmx<Boolean> bI = zzmx.m6478a(0, "gads:js_flags:mf", Boolean.valueOf(false));
    public static final zzmx<Boolean> bJ = zzmx.m6478a(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
    public static final zzmx<String> bK = zzmx.m6479a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final zzmx<String> bL = zzmx.m6479a(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzmx<Boolean> bM = zzmx.m6478a(1, "gads:enable_untrack_view_native", Boolean.valueOf(true));
    public static final zzmx<Boolean> bN = zzmx.m6478a(1, "gads:ignore_untrack_view_google_native", Boolean.valueOf(true));
    public static final zzmx<Boolean> bO = zzmx.m6478a(1, "gads:reset_listeners_preparead_native", Boolean.valueOf(true));
    public static final zzmx<Integer> bP = zzmx.m6476a(1, "gads:native_video_load_timeout", 10);
    public static final zzmx<String> bQ = zzmx.m6479a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final zzmx<Boolean> bR = zzmx.m6478a(1, "gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
    public static final zzmx<Boolean> bS = zzmx.m6478a(1, "gads:enable_store_active_view_state", Boolean.valueOf(false));
    public static final zzmx<Boolean> bT = zzmx.m6478a(1, "gads:enable_singleton_broadcast_receiver", Boolean.valueOf(false));
    public static final zzmx<Boolean> bU = zzmx.m6478a(1, "gads:native:overlay_new_fix:enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> bV = zzmx.m6478a(1, "gads:native:count_impression_for_assets", Boolean.valueOf(false));
    public static final zzmx<Boolean> bW = zzmx.m6478a(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
    public static final zzmx<Boolean> bX = zzmx.m6478a(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
    public static final zzmx<Long> bY = zzmx.m6477a(0, "gads:method_tracing:duration_ms", 30000);
    public static final zzmx<Integer> bZ = zzmx.m6476a(0, "gads:method_tracing:count", 5);
    public static final zzmx<Boolean> ba = zzmx.m6478a(1, "gads:include_lock_screen_apps_for_visibility", Boolean.valueOf(true));
    public static final zzmx<Boolean> bb = zzmx.m6478a(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
    public static final zzmx<Long> bc = zzmx.m6477a(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
    public static final zzmx<Boolean> bd = zzmx.m6478a(0, "gads:gen204_signals:enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> be = zzmx.m6478a(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> bf = zzmx.m6478a(1, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> bg = zzmx.m6478a(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
    public static final zzmx<Long> bh = zzmx.m6477a(1, "gads:network:network_prediction_timeout_ms", 2000);
    public static final zzmx<Boolean> bi = zzmx.m6478a(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
    public static final zzmx<Boolean> bj = zzmx.m6478a(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
    public static final zzmx<Boolean> bk = zzmx.m6478a(1, "gads:bypass_adrequest_service_for_inlined_mediation", Boolean.valueOf(true));
    public static final zzmx<Long> bl = zzmx.m6477a(0, "gads:resolve_future:default_timeout_ms", 30000);
    public static final zzmx<Long> bm = zzmx.m6477a(0, "gads:ad_loader:timeout_ms", 60000);
    public static final zzmx<Long> bn = zzmx.m6477a(0, "gads:rendering:timeout_ms", 60000);
    public static final zzmx<Boolean> bo = zzmx.m6478a(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
    public static final zzmx<Long> bp = zzmx.m6477a(1, "gads:gestures:task_timeout", 2000);
    public static final zzmx<Boolean> bq = zzmx.m6478a(1, "gads:gestures:btt:enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> br = zzmx.m6478a(1, "gads:gestures:sss:enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> bs = zzmx.m6478a(1, "gads:gestures:asig:enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> bt = zzmx.m6478a(1, "gads:gestures:tos:enabled", Boolean.valueOf(false));
    public static final zzmx<Integer> bu = zzmx.m6476a(1, "gads:gestures:ts", 1);
    public static final zzmx<Boolean> bv = zzmx.m6478a(1, "gads:gestures:tdvs:enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> bw = zzmx.m6478a(1, "gads:gestures:tvvs:enabled", Boolean.valueOf(false));
    public static final zzmx<String> bx = zzmx.m6479a(1, "gads:gestures:pk", "");
    public static final zzmx<Boolean> by = zzmx.m6478a(1, "gads:gestures:bs:enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> bz = zzmx.m6478a(1, "gads:gestures:check_initialization_thread:enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> f7893c = zzmx.m6478a(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
    public static final zzmx<String> cA = zzmx.m6479a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzmx<String> cB = zzmx.m6479a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzmx<String> cC = zzmx.m6479a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzmx<String> cD = zzmx.m6479a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzmx<Integer> cE = zzmx.m6476a(1, "gads:drx_debug:timeout_ms", 5000);
    public static final zzmx<Integer> cF = zzmx.m6476a(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzmx<Boolean> cG = zzmx.m6478a(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));
    public static final zzmx<Boolean> cH = zzmx.m6478a(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.valueOf(false));
    public static final zzmx<Integer> cI = zzmx.m6476a(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final zzmx<Boolean> cJ = zzmx.m6478a(1, "gads:clearcut_logging:enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> cK = zzmx.m6478a(0, "gad:force_local_ad_request_service:enabled", Boolean.valueOf(false));
    public static final zzmx<Integer> cL = zzmx.m6476a(1, "gad:http_redirect_max_count:times", 8);
    public static final zzmx<Long> cM = zzmx.m6477a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    public static final zzmx<String> cN = zzmx.m6479a(0, "gads:public_beta:traffic_multiplier", "1.0");
    public static final zzmx<Boolean> cO = zzmx.m6478a(1, "gads:real_test_request:enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> cP = zzmx.m6478a(1, "gads:real_test_request:render_webview_label", Boolean.valueOf(true));
    public static final zzmx<Boolean> cQ = zzmx.m6478a(1, "gads:real_test_request:render_native_label", Boolean.valueOf(true));
    private static zzmx<String> cR = zzmx.m6480b(0, "gads:sdk_core_experiment_id");
    private static zzmx<String> cS = zzmx.m6479a(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    private static zzmx<Boolean> cT = zzmx.m6478a(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
    private static zzmx<String> cU = zzmx.m6480b(0, "gads:request_builder:singleton_webview_experiment_id");
    private static zzmx<Boolean> cV = zzmx.m6478a(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
    private static zzmx<String> cW = zzmx.m6480b(0, "gads:sdk_use_dynamic_module_experiment_id");
    private static zzmx<String> cX = zzmx.m6480b(0, "gads:block_autoclicks_experiment_id");
    private static zzmx<String> cY = zzmx.m6480b(0, "gads:spam_app_context:experiment_id");
    private static zzmx<Integer> cZ = zzmx.m6476a(1, "gads:http_url_connection_factory:timeout_millis", (int) AbstractSpiCall.DEFAULT_TIMEOUT);
    public static final zzmx<Integer> ca = zzmx.m6476a(0, "gads:method_tracing:filesize", (int) MQEncoder.CARRY_MASK);
    public static final zzmx<Long> cb = zzmx.m6477a(1, "gads:auto_location_timeout", 2000);
    public static final zzmx<Boolean> cc = zzmx.m6478a(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
    public static final zzmx<Long> cd = zzmx.m6477a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    public static final zzmx<String> ce = zzmx.m6479a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final zzmx<String> cf = zzmx.m6479a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final zzmx<String> cg = zzmx.m6479a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final zzmx<String> ch = zzmx.m6479a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final zzmx<String> ci = zzmx.m6479a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final zzmx<Long> cj = zzmx.m6477a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    public static final zzmx<Long> ck = zzmx.m6477a(1, "gads:parental_controls:timeout", 2000);
    public static final zzmx<Boolean> cl = zzmx.m6478a(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
    public static final zzmx<Boolean> cm = zzmx.m6478a(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> cn = zzmx.m6478a(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
    public static final zzmx<Boolean> co = zzmx.m6478a(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
    public static final zzmx<Boolean> cp = zzmx.m6478a(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
    public static final zzmx<Long> cq = zzmx.m6477a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final zzmx<Boolean> cr = zzmx.m6478a(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
    public static final zzmx<Boolean> cs = zzmx.m6478a(1, "gads:http_assets_cache:enabled", Boolean.valueOf(false));
    public static final zzmx<String> ct = zzmx.m6479a(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final zzmx<Integer> cu = zzmx.m6476a(1, "gads:http_assets_cache:time_out", 100);
    public static final zzmx<Boolean> cv = zzmx.m6478a(1, "gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> cw = zzmx.m6478a(1, "gads:chrome_custom_tabs_browser:enabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> cx = zzmx.m6478a(1, "gads:chrome_custom_tabs:disabled", Boolean.valueOf(false));
    public static final zzmx<Boolean> cy = zzmx.m6478a(1, "gads:drx_in_app_preview:enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> cz = zzmx.m6478a(1, "gads:drx_debug_signals:enabled", Boolean.valueOf(true));
    public static final zzmx<String> f7894d = zzmx.m6479a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    private static zzmx<String> dA = zzmx.m6480b(0, "gads:gmsg:video_meta:experiment_id");
    private static zzmx<Long> dB = zzmx.m6477a(1, "gads:network:cache_prediction_duration_s", 300);
    private static zzmx<Boolean> dC = zzmx.m6478a(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
    private static zzmx<Boolean> dD = zzmx.m6478a(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
    private static zzmx<String> dE = zzmx.m6480b(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    private static zzmx<String> dF = zzmx.m6480b(1, "gads:sdk_core_constants:experiment_id");
    private static zzmx<Boolean> dG = zzmx.m6478a(1, "gads:js_flags:disable_phenotype", Boolean.valueOf(false));
    private static zzmx<String> dH = zzmx.m6479a(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    private static zzmx<String> dI = zzmx.m6479a(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    private static zzmx<String> dJ = zzmx.m6480b(1, "gads:singleton_webview_native:experiment_id");
    private static zzmx<Boolean> dK = zzmx.m6478a(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
    private static zzmx<String> dL = zzmx.m6481c(1, "gads:auto_location_for_coarse_permission:experiment_id");
    private static zzmx<String> dM = zzmx.m6481c(1, "gads:auto_location_timeout:experiment_id");
    private static zzmx<Long> dN = zzmx.m6477a(1, "gads:auto_location_interval", -1);
    private static zzmx<String> dO = zzmx.m6481c(1, "gads:auto_location_interval:experiment_id");
    private static zzmx<String> dP = zzmx.m6480b(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    private static zzmx<String> dQ = zzmx.m6480b(0, "gads:afs:csa:experiment_id");
    private static zzmx<Boolean> dR = zzmx.m6478a(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
    private static zzmx<Boolean> dS = zzmx.m6478a(1, "gads:parental_controls:send_from_client", Boolean.valueOf(true));
    private static zzmx<Boolean> dT = zzmx.m6478a(1, "gads:parental_controls:cache_results", Boolean.valueOf(true));
    private static zzmx<String> dU = zzmx.m6479a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static zzmx<Long> dV = zzmx.m6477a(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
    private static zzmx<Integer> dW = zzmx.m6476a(1, "gads:cache:ad_request_timeout_millis", 250);
    private static zzmx<Integer> dX = zzmx.m6476a(1, "gads:cache:max_concurrent_downloads", 10);
    private static zzmx<Long> dY = zzmx.m6477a(1, "gads:cache:javascript_timeout_millis", 5000);
    private static zzmx<Boolean> dZ = zzmx.m6478a(1, "gads:cache:connection_per_read", Boolean.valueOf(false));
    private static zzmx<String> da = zzmx.m6480b(0, "gads:video_stream_cache:experiment_id");
    private static zzmx<Boolean> db = zzmx.m6478a(0, "gads:ad_id_app_context:enabled", Boolean.valueOf(false));
    private static zzmx<Float> dc = zzmx.m6475a(0, "gads:ad_id_app_context:ping_ratio");
    private static zzmx<String> dd = zzmx.m6480b(0, "gads:ad_id_app_context:experiment_id");
    private static zzmx<String> de = zzmx.m6480b(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static zzmx<Boolean> df = zzmx.m6478a(0, "gads:ad_id_use_shared_preference:enabled", Boolean.valueOf(false));
    private static zzmx<Float> dg = zzmx.m6475a(0, "gads:ad_id_use_shared_preference:ping_ratio");
    private static zzmx<Boolean> dh = zzmx.m6478a(0, "gads:ad_id_use_persistent_service:enabled", Boolean.valueOf(false));
    private static zzmx<String> di = zzmx.m6481c(0, "gads:looper_for_gms_client:experiment_id");
    private static zzmx<Boolean> dj = zzmx.m6478a(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
    private static zzmx<String> dk = zzmx.m6480b(0, "gads:app_index:experiment_id");
    private static zzmx<String> dl = zzmx.m6480b(0, "gads:kitkat_interstitial_workaround:experiment_id");
    private static zzmx<String> dm = zzmx.m6480b(0, "gads:interstitial_follow_url:experiment_id");
    private static zzmx<Boolean> dn = zzmx.m6478a(0, "gads:analytics_enabled", Boolean.valueOf(true));
    private static zzmx<Integer> f7895do = zzmx.m6476a(0, "gads:webview_cache_version", 0);
    private static zzmx<String> dp = zzmx.m6481c(0, "gads:pan:experiment_id");
    private static zzmx<Boolean> dq = zzmx.m6478a(0, "gads:ad_serving:enabled", Boolean.valueOf(true));
    private static zzmx<Boolean> dr = zzmx.m6478a(1, "gads:impression_optimization_enabled", Boolean.valueOf(false));
    private static zzmx<String> ds = zzmx.m6479a(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static zzmx<Integer> dt = zzmx.m6476a(1, "gads:banner_ad_pool:max_queues", 3);
    private static zzmx<Integer> du = zzmx.m6476a(1, "gads:banner_ad_pool:max_pools", 3);
    private static zzmx<Integer> dv = zzmx.m6476a(1, "gads:heap_wastage:bytes", 0);
    private static zzmx<Boolean> dw = zzmx.m6478a(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
    private static zzmx<Boolean> dx = zzmx.m6478a(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
    private static zzmx<Boolean> dy = zzmx.m6478a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
    private static zzmx<Boolean> dz = zzmx.m6478a(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
    public static final zzmx<Boolean> f7896e = zzmx.m6478a(0, "gads:block_autoclicks", Boolean.valueOf(false));
    private static zzmx<Long> ea = zzmx.m6477a(1, "gads:cache:connection_timeout", 5000);
    private static zzmx<Long> eb = zzmx.m6477a(1, "gads:cache:read_only_connection_timeout", 5000);
    private static zzmx<Boolean> ec = zzmx.m6478a(0, "gads:nonagon:red_button", Boolean.valueOf(false));
    private static zzmx<Boolean> ed = zzmx.m6478a(1, "gads:nonagon:banner:enabled", Boolean.valueOf(false));
    private static zzmx<String> ee = zzmx.m6479a(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static zzmx<Boolean> ef = zzmx.m6478a(1, "gads:nonagon:interstitial:enabled", Boolean.valueOf(false));
    private static zzmx<String> eg = zzmx.m6479a(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static zzmx<Boolean> eh = zzmx.m6478a(1, "gads:nonagon:rewardedvideo:enabled", Boolean.valueOf(false));
    private static zzmx<Boolean> ei = zzmx.m6478a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", Boolean.valueOf(false));
    private static zzmx<String> ej = zzmx.m6479a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static zzmx<Boolean> ek = zzmx.m6478a(1, "gads:nonagon:nativead:enabled", Boolean.valueOf(false));
    private static zzmx<String> el = zzmx.m6479a(1, "gads:nonagon:nativead:ad_unit_exclusions", "(?!)");
    private static zzmx<Boolean> em = zzmx.m6478a(1, "gads:nonagon:service:enabled", Boolean.valueOf(false));
    private static byte[] en;
    public static final zzmx<String> f7897f = zzmx.m6479a(1, "gads:video_exo_player:version", "1");
    public static final zzmx<Integer> f7898g = zzmx.m6476a(1, "gads:video_exo_player:connect_timeout", (int) EventsFilesManager.MAX_BYTE_SIZE_PER_FILE);
    public static final zzmx<Integer> f7899h = zzmx.m6476a(1, "gads:video_exo_player:read_timeout", (int) EventsFilesManager.MAX_BYTE_SIZE_PER_FILE);
    public static final zzmx<Integer> f7900i = zzmx.m6476a(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final zzmx<Integer> f7901j = zzmx.m6476a(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzmx<Integer> f7902k = zzmx.m6476a(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzmx<Integer> f7903l = zzmx.m6476a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzmx<Long> f7904m = zzmx.m6477a(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final zzmx<Long> f7905n = zzmx.m6477a(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final zzmx<Integer> f7906o = zzmx.m6476a(1, "gads:video_stream_cache:connect_timeout_millis", (int) AbstractSpiCall.DEFAULT_TIMEOUT);
    public static final zzmx<Boolean> f7907p = zzmx.m6478a(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
    public static final zzmx<String> f7908q = zzmx.m6479a(1, "gads:video:metric_frame_hash_times", "");
    public static final zzmx<Long> f7909r = zzmx.m6477a(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final zzmx<Boolean> f7910s = zzmx.m6478a(1, "gads:video:force_watermark", Boolean.valueOf(false));
    public static final zzmx<Long> f7911t = zzmx.m6477a(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final zzmx<Boolean> f7912u = zzmx.m6478a(1, "gads:video:spinner:enabled", Boolean.valueOf(false));
    public static final zzmx<Integer> f7913v = zzmx.m6476a(1, "gads:video:spinner:scale", 4);
    public static final zzmx<Long> f7914w = zzmx.m6477a(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final zzmx<Boolean> f7915x = zzmx.m6478a(1, "gads:video:aggressive_media_codec_release", Boolean.valueOf(false));
    public static final zzmx<Boolean> f7916y = zzmx.m6478a(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
    public static final zzmx<Boolean> f7917z = zzmx.m6478a(1, "gads:memory_bundle:runtime_info", Boolean.valueOf(true));

    public static List<String> m6489a() {
        return zzkb.m6349e().m6485a();
    }

    public static void m6490a(Context context) {
        zzajk.m5302a(context, new zzni(context));
        int intValue = ((Integer) zzkb.m6350f().m6488a(dv)).intValue();
        if (intValue > 0 && en == null) {
            en = new byte[intValue];
        }
    }

    public static void m6491a(Context context, JSONObject jSONObject) {
        zzkb.m6348d();
        Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        zzkb.m6349e().m6486a(edit, jSONObject);
        zzkb.m6348d();
        edit.commit();
    }

    public static List<String> m6492b() {
        zznd e = zzkb.m6349e();
        List<String> a = e.m6485a();
        for (zzmx a2 : e.f7857c) {
            String str = (String) zzkb.m6350f().m6488a(a2);
            if (str != null) {
                a.add(str);
            }
        }
        return a;
    }
}
